[2020-01-08 16:41:19,008] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: trigger_dag.check_file_exists 2019-12-31T00:00:00+00:00 [queued]>
[2020-01-08 16:41:19,243] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: trigger_dag.check_file_exists 2019-12-31T00:00:00+00:00 [queued]>
[2020-01-08 16:41:19,245] {taskinstance.py:841} INFO - 
--------------------------------------------------------------------------------
[2020-01-08 16:41:19,249] {taskinstance.py:842} INFO - Starting attempt 1 of 1
[2020-01-08 16:41:19,273] {taskinstance.py:843} INFO - 
--------------------------------------------------------------------------------
[2020-01-08 16:41:19,531] {taskinstance.py:862} INFO - Executing <Task(FileSensor): check_file_exists> on 2019-12-31T00:00:00+00:00
[2020-01-08 16:41:19,533] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'trigger_dag', 'check_file_exists', '2019-12-31T00:00:00+00:00', '--job_id', '42', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/trigger_dag.py', '--cfg_path', '/tmp/tmphutmgomc']
[2020-01-08 16:41:23,897] {logging_mixin.py:112} INFO - [2020-01-08 16:41:23,895] {local_task_job.py:124} WARNING - Time since last heartbeat(0.15 s) < heartrate(5.0 s), sleeping for 4.846531 s
[2020-01-08 16:41:26,578] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists /usr/local/lib/python3.7/site-packages/airflow/configuration.py:226: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2020-01-08 16:41:26,579] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   FutureWarning
[2020-01-08 16:41:26,579] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists /usr/local/lib/python3.7/site-packages/airflow/config_templates/airflow_local_settings.py:65: DeprecationWarning: The elasticsearch_host option in [elasticsearch] has been renamed to host - the old setting has been used, but please update your config.
[2020-01-08 16:41:26,584] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   ELASTICSEARCH_HOST = conf.get('elasticsearch', 'HOST')
[2020-01-08 16:41:26,585] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists /usr/local/lib/python3.7/site-packages/airflow/config_templates/airflow_local_settings.py:67: DeprecationWarning: The elasticsearch_log_id_template option in [elasticsearch] has been renamed to log_id_template - the old setting has been used, but please update your config.
[2020-01-08 16:41:26,585] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   ELASTICSEARCH_LOG_ID_TEMPLATE = conf.get('elasticsearch', 'LOG_ID_TEMPLATE')
[2020-01-08 16:41:26,586] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists /usr/local/lib/python3.7/site-packages/airflow/config_templates/airflow_local_settings.py:69: DeprecationWarning: The elasticsearch_end_of_log_mark option in [elasticsearch] has been renamed to end_of_log_mark - the old setting has been used, but please update your config.
[2020-01-08 16:41:26,586] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   ELASTICSEARCH_END_OF_LOG_MARK = conf.get('elasticsearch', 'END_OF_LOG_MARK')
[2020-01-08 16:41:28,781] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists [2020-01-08 16:41:28,761] {settings.py:252} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=674
[2020-01-08 16:41:29,074] {logging_mixin.py:112} INFO - [2020-01-08 16:41:29,074] {local_task_job.py:124} WARNING - Time since last heartbeat(0.18 s) < heartrate(5.0 s), sleeping for 4.818785 s
[2020-01-08 16:41:34,513] {logging_mixin.py:112} INFO - [2020-01-08 16:41:34,513] {local_task_job.py:124} WARNING - Time since last heartbeat(0.26 s) < heartrate(5.0 s), sleeping for 4.742894 s
[2020-01-08 16:41:39,911] {logging_mixin.py:112} INFO - [2020-01-08 16:41:39,911] {local_task_job.py:124} WARNING - Time since last heartbeat(0.17 s) < heartrate(5.0 s), sleeping for 4.830213 s
[2020-01-08 16:41:45,294] {logging_mixin.py:112} INFO - [2020-01-08 16:41:45,289] {local_task_job.py:124} WARNING - Time since last heartbeat(0.13 s) < heartrate(5.0 s), sleeping for 4.872688 s
[2020-01-08 16:41:45,491] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists [2020-01-08 16:41:45,473] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-01-08 16:41:45,532] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists [2020-01-08 16:41:45,474] {dagbag.py:92} INFO - Filling up the DagBag from /usr/local/airflow/dags/trigger_dag.py
[2020-01-08 16:41:47,066] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists [2020-01-08 16:41:47,063] {cli.py:545} INFO - Running <TaskInstance: trigger_dag.check_file_exists 2019-12-31T00:00:00+00:00 [running]> on host eac77fa5e690
[2020-01-08 16:41:47,843] {taskinstance.py:1058} ERROR - The conn_id `fs_airflow` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
    while not self.poke(context):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/sensors/file_sensor.py", line 57, in poke
    hook = FSHook(self.fs_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/fs_hook.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `fs_airflow` isn't defined
[2020-01-08 16:41:47,897] {taskinstance.py:1089} INFO - Marking task as FAILED.
[2020-01-08 16:41:48,352] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists Traceback (most recent call last):
[2020-01-08 16:41:48,353] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/bin/airflow", line 37, in <module>
[2020-01-08 16:41:48,353] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     args.func(args)
[2020-01-08 16:41:48,354] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-01-08 16:41:48,354] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     return f(*args, **kwargs)
[2020-01-08 16:41:48,355] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 551, in run
[2020-01-08 16:41:48,356] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     _run(args, dag, ti)
[2020-01-08 16:41:48,358] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 469, in _run
[2020-01-08 16:41:48,362] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     pool=args.pool,
[2020-01-08 16:41:48,364] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-01-08 16:41:48,365] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     return func(*args, **kwargs)
[2020-01-08 16:41:48,366] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
[2020-01-08 16:41:48,367] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     result = task_copy.execute(context=context)
[2020-01-08 16:41:48,370] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
[2020-01-08 16:41:48,371] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     while not self.poke(context):
[2020-01-08 16:41:48,372] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/sensors/file_sensor.py", line 57, in poke
[2020-01-08 16:41:48,374] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     hook = FSHook(self.fs_conn_id)
[2020-01-08 16:41:48,374] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/fs_hook.py", line 38, in __init__
[2020-01-08 16:41:48,376] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     conn = self.get_connection(conn_id)
[2020-01-08 16:41:48,378] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
[2020-01-08 16:41:48,379] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     conn = random.choice(list(cls.get_connections(conn_id)))
[2020-01-08 16:41:48,381] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
[2020-01-08 16:41:48,385] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     conns = cls._get_connections_from_db(conn_id)
[2020-01-08 16:41:48,386] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-01-08 16:41:48,397] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     return func(*args, **kwargs)
[2020-01-08 16:41:48,399] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
[2020-01-08 16:41:48,432] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists     "The conn_id `{0}` isn't defined".format(conn_id))
[2020-01-08 16:41:48,432] {base_task_runner.py:115} INFO - Job 42: Subtask check_file_exists airflow.exceptions.AirflowException: The conn_id `fs_airflow` isn't defined
[2020-01-08 16:41:50,648] {logging_mixin.py:112} INFO - [2020-01-08 16:41:50,647] {local_task_job.py:124} WARNING - Time since last heartbeat(0.15 s) < heartrate(5.0 s), sleeping for 4.846567 s
[2020-01-08 16:41:55,497] {logging_mixin.py:112} INFO - [2020-01-08 16:41:55,495] {local_task_job.py:103} INFO - Task exited with return code 1
